### ISSUE TITLE
Re-submission Tasks 

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/generation-knit-2.0#15]
# Tasks to do for resubmission 

## From L01

No fails in this category 

From the comments: 

- [ ]  The design of the homepage could be improved to appear more aesthetically pleasing.
- [ ] Further, it might be a good idea to use the burger menu only in the mobile web view.
- [ ] Consider disabling any input fields or submit buttons when a form submission is in progress
- [ ] There are repetitive errors on almost all HTML pages

### Tasks: 

- [ ] Add knitted BG tiling to home page 
- [ ] Disable burger menu in web view 
- [ ] Enable icon menu in web view 
- [ ] Disable input fields while a task is in progress
- [ ] Lint HTML using the "View Page Source" to find and solve errors 

## From L02

No fails in this category 

From the comments: 

- [ ] All image pickers should restrict the data types that the user is able to select so that no inappropriate file types are uploaded onto the server
- [ ] Ideally, a form must be well validated and should handle incorrect/empty data intelligently. This prevents corruption of data at the database level or the entry of any malicious inputs to the system

### Tasks 

- [ ] Add validation to image pickers so only certain files are acceptable 
- [ ] Add handlers for empty data inputs 

## From L03

- [ ] Fail in 3.3: "Non logged in users can access restricted content and functionality either through on-screen elements or direct entry of the URL"

From the comments: 

- [ ] Any user regardless of login status and privileges is able to access edit links through URL. For example: https://gknit-3be52d483a34.herokuapp.com/edit/60/ can be opened directly in the incognito mode and all changes made through this link are successful. A non-logged in user is able to see the prefilled contents of the form if they edit it using the URL. No user should be able to access privileged URLs if they do not have the relevant permissions. This could lead to a massive breach of security. Appropriate redirection should be put in place on trying to access these links.

### Tasks: 

- [ ] Set page to only render if user is logged in 
- [ ] If user in not logged in, redirect to login page with a "Whoops, you don't have permission to do this" message 

## From L06:

No fails in this category 

From the comments: 

- [ ] Consider adding detailed deployment steps with specific step-wise commands with respect to the repository for the local environment along with GitHub Pages or Heroku. 

### Tasks: 

- [ ] Improve deployment section in readme.md
