### ISSUE TITLE
User Story: Deploy to Heroku

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/generation-knit-2.0#2]
As a developer, I must be able to deploy my project to Heroku so that users can access my website. This will allow me to ensure that my code is valid and the front and backend function correctly.

## Acceptance Criteria

1. Configure variables in Heroku to the necessary values for my project
2. Create Procfile and configure settings.py to work with Heroku
3. Successfully deploy to Heroku
4. Test final build before submission

## Tasks: 

- [x] Create new Heroku app
- [x] Configure config vars for Cloudinary and SQL database
- [x] Configure app settings, secret key etc.
- [x] Configure env.py for deployment
