### ISSUE TITLE
User Story: Pattern Detail Page

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/generation-knit-2.0#5]
As a user, I can view a pattern's detail page. This allows me to access details about the pattern, along with a link to the pattern OR a PDF download of the pattern

##Acceptance Criteria:
1. Each pattern has it's own pattern page
2. Pattern page shows image(s) of pattern
3. Pattern page shows fibre weight and needle size of pattern
4. Pattern page provides either a link to pattern or direct PDF download

##Tasks:
### Create Pattern app: 

- [ ] Create Pattern app
- [ ] Add appropriate URLs for pattern app, where the URL is generated from the pattern #

###  Style Pattern page:

- [ ] Create wireframe for pattern page
- [ ] Pattern page is laid out in an appealing manner that appeals to the user and adheres to UX principles
- [ ] Pattern page displays information about the pattern

### Edit/Delete Pattern:

- [ ] If the user is logged in AND they are the creator of the pattern, they can edit or delete the pattern
