### ISSUE TITLE
User Story: User Profile

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/generation-knit-2.0#6]
As a user, I can edit my profile to have a profile picture and short biography about me. This allows me to express myself to other users of the site

## Acceptance Criteria:
1. Profile has a profile picture
2. User can optionally add a short biography
3. Profile shows the patterns uploaded by the user
4. Profile shows the amount of patterns uploaded by the user

##Tasks:
###Create the Profile app:

- [ ] Upon creation of a new User at registration, a Profile is also created and assigned to that User
- [ ] Create the URL structure so that a user can visit a Profile of a user by going to profile/(user)
- [ ] Profile is designated a placeholder profile picture

### Design the Profile page:

- [ ] Create a wireframe for the Profile page
- [ ] Create a Profile page that clearly displays relevant information to the user and adheres to UX design principles
- [ ] Profile page should display a user portrait, amount of patterns created by user
- [ ] Should have an edit button  for users to edit their bio and profile image

### Editing the profile page:

- [ ] Users should be able to edit their biography and profile image
- [ ] Users should not be able to edit their username
- [ ] Users should be able to delete their profile
